setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

EthDcrMiner64.exe -epool us1.ethermine.org:14444 -ewal (YOUR PUBLIC WALLET ADDRESS).(WORKER NAME) -epsw x -allpools 1 -mode 1
